name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  source_file:  # swagger file to be validated
    description: 'Source swagger file'
    required: true
    default: 'develop.json'
  benchmark_file:  # benchmark swagger file (only required when validations !== 'schema-validation-only')
    description: 'benchmark swagger file'
    required: false
    default: 'develop.json'
  validations:
    description: 'Type of validations to be run [all (default), schema-validation-only]'
    required: true
    default: 'all'
  blocking_decision:
    description: 'Decision to be taken on remaining steps if current action fails [strict for block, none for non-block (default)]'
    required: true
    default: 'none'
outputs:
  swagger_validation_results:
    description: 'List of swagger validation errors'
  openapi_diff_results:
    description: 'List of swagger files differences'
runs:
  using: 'node20'
  main: 'dist/index.js'
